### ISSUE TITLE
Loop animation ?

### ISSUE THREAD

**Issue by elpouletorange** [qbcore-framework/progressbar#24]
Hi, I am wondering if it is possible to loop the animation ? I am using progressbar to repair cars. If the time specified is longer than the animation, the animation does not repeat itself. 
![image](https://user-images.githubusercontent.com/124886095/222568637-9695bb5e-04fe-460f-afbc-14f7ba2d730c.png)

**Comment by elpouletorange** [comment]
`

	local function RepairVehicle(veh, hp, body, time, item)
		QBCore.Functions.Progressbar("repair_vehicle", Lang:t("progress.repair_veh"), time * 1000, false, true, {
			disableMovement = true,
			disableCarMovement = true,
			disableMouse = false,
			disableCombat = true,
		}, {
			animDict = "mini@repair",
			anim = "fixing_a_player",
			flags = 16,
		}, {}, {}, function() -- Done
			StopAnimTask(PlayerPedId(), "mini@repair", "fixing_a_player", 1.0)
			QBCore.Functions.Notify(Lang:t("success.repaired_veh"))
			SetVehicleEngineHealth(veh, hp)
			SetVehicleEngineOn(veh, true, false)
			SetVehicleTyreFixed(veh, 0)
			SetVehicleTyreFixed(veh, 1)
			SetVehicleTyreFixed(veh, 2)
			SetVehicleTyreFixed(veh, 3)
			SetVehicleTyreFixed(veh, 4)
			if body then SetVehicleFixed(veh) end -- repair body if true
			if (IsBackEngine(GetEntityModel(veh))) then
				SetVehicleDoorShut(veh, 5, false)
			else
			SetVehicleDoorShut(veh, 4, false)
		end
			if item ~= nil then TriggerServerEvent('qb-vehiclefailure:removeItem', item) end -- remove item
		end, function() -- Cancel
			StopAnimTask(PlayerPedId(), "mini@repair", "fixing_a_player", 1.0)
			QBCore.Functions.Notify(Lang:t("error.failed_notification"), "error")
			if (IsBackEngine(GetEntityModel(veh))) then
				SetVehicleDoorShut(veh, 5, false)
			else
				SetVehicleDoorShut(veh, 4, false)
			end
		end)
	end
`

**Comment by DuoTheDev** [comment]
You will want to change the value of the animation flag. That is what controls the looping / other things. In your code this is `flags = 16`

I would recommend looking further into the meaning of the flags in order to properly achieve the effect you want.

Resource:
https://docs.fivem.net/natives/?_0xEA47FE3719165B94

**Comment by elpouletorange** [comment]
Ok thank you sir
